flowers = (
        ('Europe','Belgium','Wallonia'),    
        ('Africa','Nigeria','Costus spectabilis'),
        ('Oceania','New Zealand','floral emblem'),
        ('Africa','Nigeria','Acanthus montanus'),
        ('Asia','Japan','Sakura'),
        ('Africa','South Africa','King Protea'),
        ('Africa','South Africa','Protea cynaroides'),
        ('Asia','Japan','Chrysanthemum'),
        ('Asia','South Korea','Hibiscus syriacus'),
        ('Asia','Japan','Pink moss'),        
        ('Europe','Netherlands','Daisy'),        
        ('Asia','South Korea','Sunflower'),
        ('Asia','India','Lotus'),
        ('Europe','Belgium','Brussels'),
        ('Oceania','New Zealand','Hyacinth'),
        ('Europe','Belgium','Flanders'),
        ('Europe','Denmark','Daisy'),
        ('Europe','Finland','Lily of the Valley'),
        ('North America','Canada','Maple leaf'),
        ('Europe','Netherlands','Tulip'),
        ('North America','Canada','Nova Scotia'),
        ('Oceania','Australia','Golden Wattle')
    )