# Generated by Django 4.2.17 on 2025-01-11 02:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flowers.state')),
            ],
        ),
    ]
