# Generated by Django 4.2.17 on 2025-01-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
