# Generated by Django 4.2.17 on 2025-01-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.continent'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.state'),
        ),
    ]
