# Generated by Django 4.2.17 on 2025-01-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_alter_flower_continent_alter_flower_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='continent',
        ),
    ]
