# Generated by Django 4.2.17 on 2025-01-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_remove_flower_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='images_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
