# Generated by Django 4.2.17 on 2025-01-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_flower_images_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='images_link',
            new_name='image_link',
        ),
    ]
