# Generated by Django 4.2.17 on 2025-01-12 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_rename_images_link_flower_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='continent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flowers.continent'),
        ),
    ]
